postgres_cluster:
  hosts:
    patroni1:
      ansible_host: 192.168.10.5
      is_master: 'true'
    patroni2:
      ansible_host: 192.168.10.7
      is_master: 'false'
    patroni3:
      ansible_host: 192.168.10.9
      is_master: 'false'
